## Tipos de tensores

Você pode criar tensores do Pytorch  de inúmeras formas! Vamos ver primeiro os tipos de tensores que estão ao nosso dispor. Para isso, vamos converter uma listas comuns do Python em tensores do Pytorch.

NOte que a impressão dos tipos gloat32 e int64 não vêm acompanhadas do parâmetro de tipo "dtype", visto que se tratam dos tipos padrão trabalhados pelo Pytorch.

In [4]:
import torch

lista = [[1, 2, 3],
         [4, 5, 6]]

tensor = torch.Tensor(lista)
print(tensor.dtype)
print(tensor)

tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print(tensor)

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print(tensor)

tensor = torch.LongTensor(lista)
print(tensor.dtype)
print(tensor)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


##Outras formas de instaciar tensores
#A partir de array Numpy
torch.from_numpy()

In [22]:
import numpy as np

array = np.random.rand(3,4)
array = array.astype(int)
tns = torch.from_numpy(array)

print(array)
print('')
print(array.dtype)
print('')
print(tns)
print('')
print(tns.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

int64

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

torch.int64


##Tensores inicializados

Essas funções recebem como parâmetro o tamanho de cada dimensão do tensor. Aqui vamos conhecer as seguintes funções:

torch.ones() -> Crai um tensor preenchido com zeros.                
torch.zeros() -> Cria um tensor preenchido com uns.             
torch.randn() -> Cria um tensor preenchido com números aleatórios a partir de uma distribuição normal

In [49]:
tensor1 = torch.ones(2,3)
tensor2 = torch.zeros(4,5)
tensor3 = torch.randn(3,3)

print(tensor1)
print('')
print(tensor2)
print('')
print(tensor3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

tensor([[ 0.6766,  0.7782,  0.8986],
        [-1.2745, -1.0248, -0.1223],
        [-1.2174, -0.1439, -0.3668]])


##Tensor para array numpy

In [24]:
print(type(tensor))

array = tensor.data.numpy()
print(type(array))

<class 'torch.Tensor'>
<class 'numpy.ndarray'>


##Indexação
De posse dessa informação, a indexação é feita de forma similar a arrays Numpy, através da sitaxe de colchetes [ ].

In [39]:
lista2 = [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]

tensorx = torch.LongTensor(lista2)
print(tensorx.dtype)
print('')
print(tensorx)
tensorx[0,2] = 50

print('')
print(tensorx[0:2]) #Acessa a linha 0 e 1 mas não acessa a linha 2
print('')
print(tensorx[:, 2]) #Acessa todas as linhas da coluna 2
print('')
print(tensorx[0, 2])

torch.int64

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

tensor([[ 1,  2, 50],
        [ 4,  5,  6]])

tensor([50,  6,  9])

tensor(50)


##Operações com tensores

A função .item() utilizada anteriormente extrai o número de um tensor que possui um único valor, permitindo realizar as operações numéricas do Python.
Caso o item não seja extraído, operações que envolvam tensores vão retornar novos tensores.

Vale ressaltar também que operações entre tensores são realizadas ponto a ponto, operando cada elemento (i, j) do tensor t1, com o elemento (i, j) do tensor t2

In [53]:
tensor3 = torch.randn(3,3)

print(tensorx)
print(tensorx.shape)
print()
print(tensor3)
print(tensor3.shape)
print()
print(tensor3+tensorx)
print()
print(tensor3*tensorx)
print()
print(tensor3/tensorx)


tensor([[ 1,  2, 50],
        [ 4,  5,  6],
        [ 7,  8,  9]])
torch.Size([3, 3])

tensor([[-1.3681,  1.2661,  1.3092],
        [-1.3420, -0.1380, -0.5812],
        [-0.5569,  0.3361, -1.2301]])
torch.Size([3, 3])

tensor([[-0.3681,  3.2661, 51.3092],
        [ 2.6580,  4.8620,  5.4188],
        [ 6.4431,  8.3361,  7.7699]])

tensor([[ -1.3681,   2.5322,  65.4594],
        [ -5.3679,  -0.6898,  -3.4872],
        [ -3.8986,   2.6891, -11.0709]])

tensor([[-1.3681,  0.6331,  0.0262],
        [-0.3355, -0.0276, -0.0969],
        [-0.0796,  0.0420, -0.1367]])


##Função .size() e .view()

Uma operação **importantíssima** na manipulação de tensores para deep learning é a reorganização das suas dimensões. Dessa forma podemos, por exemplo, **linarizar um tensor n-dimensional.**

In [62]:
print(tensorx.size(0))
print(tensorx.size())
print()

tensor4 = torch.randn(4, 3)
print(tensor4)
tensor4 = tensor4.view(12)
print(tensor4)
print()
tensor4 = tensor4.view(tensor4.size(0), -1)
print(tensor4)

3
torch.Size([3, 3])

tensor([[ 0.0622, -0.7842, -0.3373],
        [ 0.3011, -0.5294,  0.2643],
        [-0.1610,  1.9975,  0.4554],
        [-0.6714, -1.0703, -0.7920]])
tensor([ 0.0622, -0.7842, -0.3373,  0.3011, -0.5294,  0.2643, -0.1610,  1.9975,
         0.4554, -0.6714, -1.0703, -0.7920])

tensor([[ 0.0622],
        [-0.7842],
        [-0.3373],
        [ 0.3011],
        [-0.5294],
        [ 0.2643],
        [-0.1610],
        [ 1.9975],
        [ 0.4554],
        [-0.6714],
        [-1.0703],
        [-0.7920]])


##GPU Cast
Para que seu script dê suporte a infraestrutura com e sem GPU, é importante definir o dispositivo no ínicio do seu código de acordo com a verificação apresentada a seguir. Essa definição de dispositivo será utilizada toda vez que precisamos subir valores na GPU, como os pesos da rede, os gradientes e etc.

In [64]:
if torch.cuda.is_available():
  device = torch.devide('cuda')
else:
  device = torch.device('cpu')
print(device)

cpu
